// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CTRL_BUS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of lev0
//        bit 31~0 - lev0[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of lev1
//        bit 31~0 - lev1[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of lev2
//        bit 31~0 - lev2[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of lev3
//        bit 31~0 - lev3[31:0] (Read/Write)
// 0x2c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XMIXER_CTRL_BUS_ADDR_LEV0_DATA 0x10
#define XMIXER_CTRL_BUS_BITS_LEV0_DATA 32
#define XMIXER_CTRL_BUS_ADDR_LEV1_DATA 0x18
#define XMIXER_CTRL_BUS_BITS_LEV1_DATA 32
#define XMIXER_CTRL_BUS_ADDR_LEV2_DATA 0x20
#define XMIXER_CTRL_BUS_BITS_LEV2_DATA 32
#define XMIXER_CTRL_BUS_ADDR_LEV3_DATA 0x28
#define XMIXER_CTRL_BUS_BITS_LEV3_DATA 32

