// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XMIXER_H
#define XMIXER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmixer_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_bus_BaseAddress;
} XMixer_Config;
#endif

typedef struct {
    u32 Ctrl_bus_BaseAddress;
    u32 IsReady;
} XMixer;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMixer_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMixer_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMixer_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMixer_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMixer_Initialize(XMixer *InstancePtr, u16 DeviceId);
XMixer_Config* XMixer_LookupConfig(u16 DeviceId);
int XMixer_CfgInitialize(XMixer *InstancePtr, XMixer_Config *ConfigPtr);
#else
int XMixer_Initialize(XMixer *InstancePtr, const char* InstanceName);
int XMixer_Release(XMixer *InstancePtr);
#endif


void XMixer_Set_lev0(XMixer *InstancePtr, u32 Data);
u32 XMixer_Get_lev0(XMixer *InstancePtr);
void XMixer_Set_lev1(XMixer *InstancePtr, u32 Data);
u32 XMixer_Get_lev1(XMixer *InstancePtr);
void XMixer_Set_lev2(XMixer *InstancePtr, u32 Data);
u32 XMixer_Get_lev2(XMixer *InstancePtr);
void XMixer_Set_lev3(XMixer *InstancePtr, u32 Data);
u32 XMixer_Get_lev3(XMixer *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
