// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmixer.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMixer_CfgInitialize(XMixer *InstancePtr, XMixer_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMixer_Set_lev0(XMixer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMixer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMIXER_CTRL_BUS_ADDR_LEV0_DATA, Data);
}

u32 XMixer_Get_lev0(XMixer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMixer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMIXER_CTRL_BUS_ADDR_LEV0_DATA);
    return Data;
}

void XMixer_Set_lev1(XMixer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMixer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMIXER_CTRL_BUS_ADDR_LEV1_DATA, Data);
}

u32 XMixer_Get_lev1(XMixer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMixer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMIXER_CTRL_BUS_ADDR_LEV1_DATA);
    return Data;
}

void XMixer_Set_lev2(XMixer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMixer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMIXER_CTRL_BUS_ADDR_LEV2_DATA, Data);
}

u32 XMixer_Get_lev2(XMixer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMixer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMIXER_CTRL_BUS_ADDR_LEV2_DATA);
    return Data;
}

void XMixer_Set_lev3(XMixer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMixer_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XMIXER_CTRL_BUS_ADDR_LEV3_DATA, Data);
}

u32 XMixer_Get_lev3(XMixer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMixer_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XMIXER_CTRL_BUS_ADDR_LEV3_DATA);
    return Data;
}

